export const ERR_NOT_FOUND_BOOKING = 'ERR_NOT_FOUND_BOOKING';
export const ERR_NOT_FOUND_QUOTE = 'ERR_NOT_FOUND_QUOTE';
export const ERR_NOT_FOUND_TALK = 'ERR_NOT_FOUND_TALK';
export const ERR_NOT_FOUND_DOCUMENT_VALIDATION =
  'ERR_NOT_FOUND_DOCUMENT_VALIDATION';
export const ERR_NOT_CREATED_TALK = 'ERR_NOT_CREATED_TALK';
export const ERR_NOT_CREATED_UNIT = 'ERR_NOT_CREATED_UNIT';
export const ERR_UNIT_NOT_FOUND = 'ERR_UNIT_NOT_FOUND';
export const ERR_PICTURE_NOT_FOUND = 'ERR_PICTURE_NOT_FOUND';
export const ERR_FLOOR_NOT_FOUND = 'ERR_FLOOR_NOT_FOUND';
export const ERR_LOGO_META_DATA_NOT_FOUND = 'ERR_LOGO_META_DATA_NOT_FOUND';
export const ERR_DUPLICATE_UNIT_FOR_LOGO_META_DATA =
  'ERR_DUPLICATE_UNIT_FOR_LOGO_META_DATA';
export const ERR_UNIT_GROUP_NOT_FOUND = 'ERR_UNIT_GROUP_NOT_FOUND';
export const ERR_UNIT_WITH_BOOKING_CANNOT_BE_DELETED =
  'ERR_UNIT_WITH_BOOKING_CANNOT_BE_DELETED';
export const ERR_CANNOT_DELETE_GROUP_INIT = 'ERR_CANNOT_DELETE_GROUP_INIT';
export const ERR_THIS_UNIT_IS_NOT_A_GROUP = 'ERR_THIS_UNIT_IS_NOT_A_GROUP';
export const ERR_NOT_CREATED_VALIDATION = 'ERR_NOT_CREATED_VALIDATION';
export const ERR_NOT_COMPLETED_VALIDATION = 'ERR_NOT_COMPLETED_VALIDATION';
export const ERR_NOT_FOUND_VALIDATION = 'ERR_NOT_FOUND_VALIDATION';
export const ERR_NOT_FOUND_MIX = 'ERR_NOT_FOUND_MIX';
export const ERR_NOT_FOUND_MIX_CATEGORY = 'ERR_NOT_FOUND_MIX_CATEGORY';
export const ERR_NOT_CREATED_NOTIFICATION = 'ERR_NOT_CREATED_NOTIFICATION';
export const ERR_NOT_FOUND_CLIENT_ID = 'ERR_NOT_FOUND_CLIENT_ID';
export const ERR_MIX_NOT_CREATED = 'ERR_MIX_NOT_CREATED';
export const ERR_RETAIL_CENTER_NOT_CREATED = 'ERR_RETAIL_CENTER_NOT_CREATED';
export const ERR_NOT_FOUND_RETAIL_CENTER = 'ERR_NOT_FOUND_RETAIL_CENTER';
export const ERR_MIX_CATEGORY_NOT_CREATED = 'ERR_MIX_CATEGORY_NOT_CREATED';
export const ERR_NOT_FOUND_BRAND = 'ERR_NOT_FOUND_BRAND';
export const ERR_NOT_CREATED_BRAND = 'ERR_NOT_CREATED_BRAND';
export const ERR_NOT_FOUND_COMPANY = 'ERR_NOT_FOUND_COMPANY';
export const ERR_NOT_CREATED_COMPANY = 'ERR_NOT_CREATED_COMPANY';
export const ERR_NOT_FOUND_FILE_OR_DIRECTORY =
  'ERR_NOT_FOUND_FILE_OR_DIRECTORY';
export const ERR_NOT_FOUND_PLAN = 'ERR_NOT_FOUND_PLAN';
export const FILE_SERVER_ERROR = 'FILE_SERVER_ERROR';
export const ERR_NOT_FOUND_EMAIL_TEMPLATE = 'ERR_NOT_FOUND_EMAIL_TEMPLATE';
export const ERR_NOT_FOUND_MESSAGE_NOTIFICATION =
  'ERR_NOT_FOUND_MESSAGE_NOTIFICATION';
export const ERR_PROSPECT_REQUEST_NOT_CREATED =
  'ERR_PROSPECT_REQUEST_NOT_CREATED';
export const ERR_COMPANY_GROUP_NOT_CREATED = 'ERR_COMPANY_GROUP_NOT_CREATED';
export const ERR_FORCASTS_NOT_CREATED = 'ERR_FORCASTS_NOT_CREATED';
export const ERR_FORCASTS_NOT_UPDATED = 'ERR_FORCASTS_NOT_UPDATED';
export const ERR_BOOKING_NOT_UPDATED = 'ERR_BOOKING_NOT_UPDATED';
export const ERR_BOOKING_NOT_CREATED = 'ERR_BOOKING_NOT_CREATED';
export const ERR_INVALID_COLOR = 'ERR_INVALID_COLOR';
export const ERR_FORCASTS_NOT_FOUND = 'ERR_FORCASTS_NOT_FOUND';
export const ERR_NOT_FOUND_REQUEST = 'ERR_NOT_FOUND_REQUEST';
export const ERR_NOT_FOUND_CONTACT = 'ERR_NOT_FOUND_CONTACT';
export const ERR_NOT_FOUND_USER = 'ERR_NOT_FOUND_USER';
export const ERR_SEND_PRESENTATION = 'ERR_SEND_PRESENTATION';
export const ERR_NOT_FOUND_GROUP_COMPANY = 'ERR_NOT_FOUND_GROUP_COMPANY';
export const ERR_UNAUTHORIZED_DELETE = 'ERR_UNAUTHORIZED_DELETE';
export const ERR_UNAUTHORIZED = 'Action non-autorisé';
export const ERR_UNAUTHORIZED_CLIENT_ID = 'ERR_UNAUTHORIZED_CLIENT_ID';
export const ERR_DELETE_BOOKING = 'ERR_DELETE_BOOKING';
export const ERR_BRAND_ALREADY_EXIST = 'ERR_BRAND_WITH_THIS_NAME_ALREADY_EXIST';
