import * as bcrypt from 'bcrypt';
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedUsers() {
  console.log('Seeding Roles');

  const roles = await prisma.userRole.createMany({
    data: [
      {
        id: 1,
        name: 'ADMIN_SQFT',
        title: 'SquareFeet Admin',
      },
      {
        id: 2,
        name: 'USER_SQFT',
        title: 'User sqft',
      },
      {
        id: 3,
        name: 'LEGAL',
        title: 'Legal',
      },
      {
        id: 4,
        name: 'ASSET_MANAGEMENT',
        title: 'Directeur Asset Management',
      },
      {
        id: 5,
        name: 'LONGTERM',
        title: 'Direction Long-term Leasing',
      },
      {
        id: 6,
        name: 'TECHNICAL',
        title: 'Technical',
      },
      {
        id: 8,
        name: 'PROPERTY',
        title: 'Property Management',
      },
      {
        id: 9,
        name: 'PORTFOLIO',
        title: 'Portfolio Management',
      },
      {
        id: 10,
        name: 'COMMERCIAL',
        title: 'Direction Commerciale',
      },
      {
        id: 11,
        name: 'SPECIALTY',
        title: 'Direction Specialty Leasing',
      },
      {
        id: 12,
        name: 'MALL_MANAGEMENT',
        title: 'Mall Management',
      },
      {
        id: 13,
        name: 'ARADEI_ADMIN',
        title: 'Aradei Admin',
      },
      {
        id: 14,
        name: 'MEDIA',
        title: 'Media',
      },
      {
        id: 15,
        name: 'CONTENT_VALIDATOR',
        title: 'Content Validator',
      },
      {
        id: 20,
        name: 'LONGTERM',
        title: 'Pôle Long-term',
      },
      {
        id: 21,
        name: 'SPECIALTY',
        title: 'Pôle Specialty',
      },
      {
        id: 22,
        name: 'ASSET_MANAGEMENT',
        title: 'Asset Management',
      },
      {
        id: 23,
        name: 'MALL_MANAGEMENT',
        title: 'Directeur Mall Management',
      },
      {
        id: 24,
        name: 'MARKETING_MANAGER',
        title: 'Marketing Manager',
      },
      {
        id: 25,
        name: 'DESIGN_DELIVERY_MANAGER',
        title: 'Design & Delivery Manager',
      },
      {
        id: 26,
        name: 'ESG_MANAGER',
        title: 'ESG Manager',
      },
      {
        id: 27,
        name: 'EVENTS_MANAGER',
        title: 'Events Manager',
      },
      {
        id: 28,
        name: 'REPORTING_MANAGER',
        title: 'Reporting Manager',
      },
      {
        id: 99,
        name: 'LEAD',
        title: 'Lead',
      },
      {
        id: 100,
        name: 'FORM',
        title: 'Form',
      },
    ],
  });
  console.log('Seeding Users');
  await prisma.userProfile.create({
    data: {
      id: '000000000000',
      email: 'buisine+1000@gmail.com',
      firstName: 'firstName',
      jobTitle: 'Employee',
      name: 'name',
      phone: '0132147811',
      mobilePhone: '0711553268',
      picture: 'default',
      roleId: 100,
      password: bcrypt.hashSync('seriously17Aspect', 8),
    },
  });

  await prisma.userProfile.createMany({
    data: [
      {
        email: 'asset.manager.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'Employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0711553268',
        picture: 'default',
        roleId: 22,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'sqft.user.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'Directeur juridique',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0711553268',
        picture: 'default',
        roleId: 10,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'legal.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 3,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'user.sqft.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 2,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'malaouifr@gmail.com',
        firstName: 'firstname',
        jobTitle: 'Employee',
        name: 'name',
        phone: '0112458545',
        mobilePhone: '0622147833',
        picture: 'default',
        roleId: 1,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'giujk@jhk.jnk',
        firstName: 'firstname',
        jobTitle: 'uighjk',
        name: 'name',
        phone: 'uhijk',
        mobilePhone: 'uihjk',
        picture: 'default',
        roleId: 12,
        password:
          '$2b$08$8/KFcbCWIKlJABSuJrzh5.l7ZCb0DrJKw/TJgxPDhEl/iqy9KqKh2',
      },
      {
        email: 'lead.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 99,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'technical.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 6,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'director.mall.manager.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 23,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'media.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 14,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'director.specialty.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 11,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'pole.specialty.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 21,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'asset.manager.director.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 4,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'director.longterm.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 5,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'form.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 100,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'pole.longterm.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 20,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'portfolio.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 9,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'aradei.admin.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 13,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'mall.manager.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 12,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'content.validator.specialty.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 15,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
      {
        email: 'property.squarefeet@gmail.com',
        firstName: 'firstname',
        jobTitle: 'employee',
        name: 'name',
        phone: '0132147811',
        mobilePhone: '0132147811',
        picture: 'default',
        roleId: 8,
        password: bcrypt.hashSync('seriously17Aspect', 8),
      },
    ],
  });
}
