export const carrefourSidiMaaroufRetailCenter = {
  "alias": "CFSM",
  "address": "Sidi Maarouf",
  "logo": "/uploads/logos/carrefour.jpg",
  "city": "Casablanca",
  "country": "Maroc",
  "type": 1,
  "specialty": 1,
  "ownerEntity": "GOLF I",
  "headquarters": "Route des Zaërs KM 3,5 - 10000 Rabat",
  "legalPersonTitle": "Mr",
  "legalPersonName": "Nom",
  "legalPersonFirstname": "Prenom",
  "legalPersonRC": "111915",
  "legalPersonCityRC": "Rabat",
  "flagShip": "Carrefour",
  "parkingSpaces": 800,
  "annualVisitors": 42000000,
  "name": "Carrefour Sidi Maarouf",
  "description": "L’actif est situé dans le quartier de Sidi Maârouf, à proximité de la route principale de Bouskoura et de l’aéroport. Accessible depuis la route de Nouaceur, le site est entouré de quartiers résidentiels, commerciaux et de bureaux très fréquentés. Il est visible et très bien desservi par les transports en commun.\nLe Carrefour Sidi Maârouf sera doté d’un Box Park sur une parcelle de 2.000 m², en plein cœur du parking du Retail Park.\nL’objectif est de créer une centralité dans le quartier Sidi Maarouf et d’accroitre l’attractivité de la zone en offrant des commerces, services et espaces de restauration.\n",
  "picture": "/uploads/images/retail-centers/carrefour-sidi-maarouf.jpg",
  "openingYear": 2015,
  "surface": 15000,
  "floors": [
    {
      "id": 1,
      "name": "RDC",
      "svgBluePrint": "/uploads/plans/carrefourSidiMaarouf/Plan_carrefourSidiMaarouf_RDC.svg",
      "units": [
        {
          "unitId": "R004",
          "alias": "",
          "company": "yhlqb9dsb4uyh4jplki5j7po",
          "brand": "alm4rd0n24kddys4ldzr7ors",
          "leaseFrom": "2015-12-01T00:00:00.000Z",
          "leaseTo": "2023-11-29T23:00:00.000Z",
          "surface": 125,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        },
        {
          "unitId": "R002",
          "alias": "",
          "company": "p8xncejna6wwkddmcwiei0k3",
          "brand": "f41dgk3rpl1jtuvo8gp0gzmy",
          "leaseFrom": "2015-12-01T00:00:00.000Z",
          "leaseTo": "2023-11-29T23:00:00.000Z",
          "surface": 370,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        },
        {
          "unitId": "R001",
          "alias": "",
          "company": "aqh9njt25o1echmvkzih92bp",
          "brand": "mktn3mnek19tghajvblzbw42",
          "leaseFrom": "2019-06-30T23:00:00.000Z",
          "leaseTo": "2032-11-29T00:00:00.000Z",
          "surface": 14166,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        },
        {
          "unitId": "R005",
          "alias": "",
          "company": "vhr74lq5hgxedsx9vvani5mn",
          "brand": "r03odbibdvngkgwd4m8143ug",
          "leaseFrom": "2019-06-30T23:00:00.000Z",
          "leaseTo": "2032-11-29T00:00:00.000Z",
          "surface": 125,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        },
        {
          "unitId": "R003",
          "alias": "",
          "company": "",
          "brand": "",
          "leaseFrom": "2005-01-01T00:00:00.000Z",
          "leaseTo": "2030-12-30T00:00:00.000Z",
          "surface": 40,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        },
        {
          "unitId": "PARK1",
          "alias": "",
          "company": "",
          "brand": "",
          "leaseFrom": "2015-11-01T00:00:00.000Z",
          "leaseTo": "2025-10-31T23:00:00.000Z",
          "surface": 64,
          "floor": "RDC",
          "rentType": 1,
          "terrasse": 0,
          "mezzanine": 0,
          "specialty": ""
        }
      ]
    }
  ]
}